### ISSUE TITLE
QuerySelector Error, url's with and query

### ISSUE THREAD

**Issue by ghost** [Juicy/juicy-display-router#1]
When navigating to this url

```
http://localhost:8080/launcher/workspace/Calendar?view=agendaDay&day=2015-01-28
```

I get this error in the console:

```
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '.workspace.Calendar?view=agendaDay&day=2015-01-28' is not a valid selector.
```

**Comment by warpech** [comment]
This is an error in the way `warpech-display-router` is used (in this case the Launcher app).

I just checked and it looks that the problem has been fixed there. Closing.
