### ISSUE TITLE
Migrate to Juicy organisation

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-display-router#2]

**Comment by warpech** [comment]
After renaming to `juicy-display-router` it should be released as version 1.0.0

**Comment by miyconst** [comment]
@warpech 

http://warpech.github.io/warpech-display-router
What about the demo? It seems like it is not available any more.

**Comment by warpech** [comment]
The demo link works now after fixing the README. Could you create the git tag, so that Bower and GitHub Releases picks up the new version?

**Comment by miyconst** [comment]
Done.

https://github.com/Juicy/juicy-display-router/releases
